import Head from "next/head";
import Hero from "../components/Hero";
import Menu from "../components/Menu";
import Offers from "../components/Offers";
import {client, urlFor} from '../lib/client'
import useStore  from "../lib/store";
import Contact from '../components/Contact'

/**
 * token , fooddeli_token
 * @returns skU3w10wWbxM1vKwvnhKY41wj7mZXdUYjV1QRjTehhYs7iPEtTRACUNCTvijrAl4hcCImlRYU33pgcpzCOoAjSp8o0udF1mi5XPVEPX6ChS8FZElkyEBqEBz6I1ez1pTmtvsfbTmz7tpqgmFld2NIdPXymOn3UjAM781J2DQbdp9tHTikAvg
 */

export default function Home({pizza}) {
  const state = useStore(state => state)
  console.log({state})
  return (
    <>
      <Head>
        <title>FUDO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      {/* body */}
      <main className="px-1">
        <Hero />
        <Offers />
        <Menu pizza = {pizza}/>
        <Contact />
      </main>
    </>
  );
}


// fetch data
export async function getServerSideProps() {
  const pizza = await client.fetch(`*[_type == "pizza"]`);
  return {
    props: {
      pizza,
    },
  };
}
